spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leafblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  profiles:
    active: dev
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml


jwt:
  tokenHeader: Authorization
  secret: jwtKey
  expiration: 86400
  tokenHead: Bearer

server:
  port: 8088

logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug

secure:
  ignored:
    urls: #安全路径白名单
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /user/login
      - /user/register
      - /user/info
      - /user/logout